
// Login
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';

// Logout
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';

// Forgot Password
export const REQUEST_RESET_PASSWORD = 'REQUEST_RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

// Get Current User
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_LEARNERS = 'GET_ALL_LEARNERS';
export const GET_ALL_LECTURERS = 'GET_ALL_LECTURERS';

// App Template
export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE';
export const FULL_SCREEN = 'FULL_SCREEN';
export const FULL_SCREEN_EXIT = 'FULL_SCREEN_EXIT';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const NAV_CONTENT_LEAVE = 'NAV_CONTENT_LEAVE';
export const NAV_COLLAPSE_LEAVE = 'NAV_COLLAPSE_LEAVE';
